# Generated by Django 4.2.29 on 2026-08-04 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etichetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('colore', models.CharField(default='#0d6efd', max_length=7)),
            ],
            options={
                'verbose_name': 'Etichetta',
                'verbose_name_plural': 'Etichette',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('colore', models.CharField(default='#6c757d', help_text='Colore hex del pallino progetto (es. #0d6efd).', max_length=7)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('archiviato', models.BooleanField(default=False, help_text='Un progetto archiviato sparisce dalla sidebar e dai form, ma le sue task restano consultabili.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progetti_task_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('priorita', models.PositiveSmallIntegerField(choices=[(1, 'P1 - Urgente'), (2, 'P2 - Alta'), (3, 'P3 - Media'), (4, 'P4 - Normale')], default=4)),
                ('scadenza', models.DateTimeField(blank=True, null=True)),
                ('visibilita', models.CharField(choices=[('tutti', 'Visibile a tutti'), ('riservata', 'Riservata (solo creatore e assegnatari)')], default='tutti', max_length=10)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('completata', models.BooleanField(default=False)),
                ('completata_il', models.DateTimeField(blank=True, null=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('assegnatari', models.ManyToManyField(blank=True, related_name='task_assegnate', to=settings.AUTH_USER_MODEL)),
                ('completata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_completate', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_create', to=settings.AUTH_USER_MODEL)),
                ('etichette', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.etichetta')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sottotask', to='tasks.task')),
                ('progetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.progetto')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task',
                'ordering': ['completata', 'priorita', models.OrderBy(models.F('scadenza'), nulls_last=True), '-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='CommentoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenti_task', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Commento task',
                'verbose_name_plural': 'Commenti task',
                'ordering': ['creato_il'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completata', 'scadenza'], name='tasks_task_complet_a53587_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['progetto', 'completata'], name='tasks_task_progett_3bea89_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent'], name='tasks_task_parent__383e16_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('priorita__gte', 1), ('priorita__lte', 4)), name='task_priorita_1_4'),
        ),
    ]
