# Generated by Django 4.2.29 on 2026-10-10 14:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cq', '0010_esito_3_livelli'),
        ('ordini', '0016_ordine_vendita_prodotti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_programmi_portale_priorita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codice', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('vendita', 'Prodotto in vendita'), ('consumabile', 'Consumabile'), ('strumento', 'Strumento')], default='consumabile', max_length=15)),
                ('categoria', models.CharField(blank=True, max_length=60)),
                ('unita', models.CharField(default='pz', max_length=20, verbose_name='Unità di misura')),
                ('quantita', models.IntegerField(default=0, verbose_name='Quantità in magazzino')),
                ('scorta_minima', models.IntegerField(default=0)),
                ('traccia_scorte', models.BooleanField(default=True, help_text='Se spento la quantità non viene controllata (illimitata)')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Costo unitario')),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assegnazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('stato', models.CharField(choices=[('in_uso', 'In uso'), ('usurato', 'Usurato / da sostituire'), ('rotto', 'Rotto'), ('smarrito', 'Smarrito'), ('esaurito', 'Esaurito'), ('restituito', 'Restituito'), ('sostituito', 'Sostituito')], default='in_uso', max_length=12)),
                ('in_apertura', models.BooleanField(default=True, verbose_name='Controlla a inizio turno')),
                ('in_chiusura', models.BooleanField(default=True, verbose_name='Controlla a fine turno')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('da_gestire', models.BooleanField(default=False)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to='magazzino.articolo')),
                ('assegnata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assegnazioni_fatte', to=settings.AUTH_USER_MODEL)),
                ('origine', models.ForeignKey(blank=True, help_text="Assegnazione da cui e' stata divisa o che sostituisce", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivate', to='magazzino.assegnazione')),
                ('postazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni_magazzino', to='cq.postazionecq')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni_magazzino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assegnazione',
                'verbose_name_plural': 'Assegnazioni',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Consegna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('numero_ddt', models.CharField(blank=True, max_length=50, verbose_name='N° DDT / bolla')),
                ('note', models.TextField(blank=True)),
                ('registrata_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consegna',
                'verbose_name_plural': 'Consegne',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=150)),
                ('partita_iva', models.CharField(blank=True, max_length=20, verbose_name='P.IVA')),
                ('referente', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='OrdineFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviato', 'Inviato'), ('parziale', 'Consegnato in parte'), ('evaso', 'Evaso'), ('annullato', 'Annullato')], default='bozza', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_fornitori', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='magazzino.fornitore')),
            ],
            options={
                'verbose_name': 'Ordine fornitore',
                'verbose_name_plural': 'Ordini fornitori',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StatoAssegnazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_stato', models.CharField(blank=True, max_length=12)),
                ('a_stato', models.CharField(max_length=12)),
                ('quantita', models.PositiveIntegerField()),
                ('origine', models.CharField(choices=[('magazzino', 'Magazzino'), ('operatore', 'Operatore'), ('checklist', 'Checklist turno')], default='magazzino', max_length=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('assegnazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storico', to='magazzino.assegnazione')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stati_assegnazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RigaOrdineFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_ordine', to='magazzino.articolo')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='magazzino.ordinefornitore')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='RigaConsegna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_consegna', to='magazzino.articolo')),
                ('consegna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='magazzino.consegna')),
                ('riga_ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe_consegna', to='magazzino.rigaordinefornitore')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carico', 'Carico'), ('consegna', 'Consegna fornitore'), ('vendita', 'Vendita'), ('assegnazione', 'Assegnazione'), ('rientro', 'Rientro'), ('scarto', 'Scarto'), ('rettifica', 'Rettifica inventario')], max_length=15)),
                ('quantita', models.IntegerField(help_text='Positivo = entra in magazzino, negativo = esce')),
                ('quantita_prima', models.IntegerField()),
                ('quantita_dopo', models.IntegerField()),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='magazzino.articolo')),
                ('assegnazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti', to='magazzino.assegnazione')),
                ('consegna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti', to='magazzino.consegna')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_magazzino', to=settings.AUTH_USER_MODEL)),
                ('ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_magazzino', to='ordini.ordine')),
            ],
            options={
                'verbose_name': 'Movimento di magazzino',
                'verbose_name_plural': 'Movimenti di magazzino',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='consegna',
            name='fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consegne', to='magazzino.fornitore'),
        ),
        migrations.AddField(
            model_name='consegna',
            name='ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consegne', to='magazzino.ordinefornitore'),
        ),
        migrations.AddField(
            model_name='consegna',
            name='registrata_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consegne_registrate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articolo',
            name='fornitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='magazzino.fornitore', verbose_name='Fornitore abituale'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='prodotto',
            field=models.OneToOneField(blank=True, help_text='La vendita in cassa di questo prodotto scarica il magazzino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articolo', to='core.servizioprodotto', verbose_name='Prodotto del catalogo'),
        ),
    ]
