# Generated by Django 4.2.29 on 2026-10-10 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_articoli_dai_prodotti'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='contenuto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Contenuto di un pezzo'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='prezzo_per',
            field=models.CharField(choices=[('pezzo', 'Al pezzo'), ('contenuto', "All'unità di misura (kg, litro...)")], default='pezzo', max_length=10, verbose_name='Prezzo indicato'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='unita_contenuto',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('l', 'litri'), ('ml', 'ml')], max_length=5, verbose_name='Unità del contenuto'),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='costo',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Costo al pezzo'),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='unita',
            field=models.CharField(default='pz', help_text='Come si contano: pz, bidoni, flaconi, confezioni...', max_length=20, verbose_name='Unità di conteggio'),
        ),
        migrations.AlterField(
            model_name='rigaconsegna',
            name='prezzo',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo al pezzo'),
        ),
        migrations.AlterField(
            model_name='rigaordinefornitore',
            name='prezzo',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo al pezzo'),
        ),
    ]
