# Generated by Django 4.2.29 on 2026-10-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0003_contenuto_e_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='foto_aggiornata',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='FotoArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dati', models.BinaryField()),
                ('tipo', models.CharField(default='image/jpeg', max_length=30)),
                ('articolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='magazzino.articolo')),
            ],
            options={
                'verbose_name': 'Foto articolo',
                'verbose_name_plural': 'Foto articoli',
            },
        ),
    ]
