# Generated by Django 4.2.29 on 2026-10-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_togli_prodotti_senza_magazzino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descrizione', models.CharField(blank=True, max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Posti',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='articolo',
            name='avvertenze',
            field=models.TextField(blank=True, help_text='Sicurezza, protezioni, cosa non fare'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='diluizione',
            field=models.CharField(blank=True, help_text='es. 1:20, puro, 50 ml in 10 l', max_length=100),
        ),
        migrations.AddField(
            model_name='articolo',
            name='modo_uso',
            field=models.TextField(blank=True, verbose_name="Modo d'uso"),
        ),
        migrations.AddField(
            model_name='articolo',
            name='uso_portale',
            field=models.BooleanField(default=False, verbose_name='Portale'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='uso_self',
            field=models.BooleanField(default=False, verbose_name='Self service'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='uso_servito',
            field=models.BooleanField(default=False, verbose_name='Servito'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='magazzino.posto'),
        ),
    ]
