# Generated by Django 4.2.29 on 2026-10-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0006_posto_uso_scheda'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='link_produttore',
            field=models.URLField(blank=True, help_text='Pagina del prodotto sul sito del produttore', max_length=500, verbose_name='Link produttore'),
        ),
    ]
