# Generated by Django 4.2.29 on 2026-04-15 08:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cq', '0007_prerequisiti_turni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordini', '0004_ordine_durata_modificata_manualmente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessioneTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateTimeField(auto_now_add=True)),
                ('data_fine', models.DateTimeField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('chiuso', 'Chiuso')], default='attivo', max_length=10)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_turno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessione turno',
                'verbose_name_plural': 'Sessioni turno',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='LavorazioneOperatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fine', models.DateTimeField(blank=True, null=True)),
                ('pausa_inizio', models.DateTimeField(blank=True, null=True)),
                ('tempo_pausa_totale', models.DurationField(default=datetime.timedelta)),
                ('stato', models.CharField(choices=[('in_lavorazione', 'In Lavorazione'), ('in_pausa', 'In Pausa'), ('completato', 'Completato')], default='in_lavorazione', max_length=20)),
                ('blocco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cq.bloccopostazione')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavorazioni_operatore', to='ordini.ordine')),
                ('postazione_cq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cq.postazionecq')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavorazioni', to='turni.sessioneturno')),
            ],
            options={
                'verbose_name': 'Lavorazione operatore',
                'verbose_name_plural': 'Lavorazioni operatore',
                'ordering': ['-inizio'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Voce checklist')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('blocco', models.ForeignKey(blank=True, help_text='Se vuoto, la voce vale per tutta la postazione', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='cq.bloccopostazione')),
                ('postazione_cq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='cq.postazionecq')),
            ],
            options={
                'verbose_name': 'Voce checklist',
                'verbose_name_plural': 'Voci checklist',
                'ordering': ['postazione_cq__ordine', 'blocco__ordine', 'ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PostazioneTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turni', to='cq.bloccopostazione')),
                ('postazione_cq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turni', to='cq.postazionecq')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postazioni', to='turni.sessioneturno')),
            ],
            options={
                'verbose_name': 'Postazione turno',
                'verbose_name_plural': 'Postazioni turno',
                'unique_together': {('sessione', 'postazione_cq', 'blocco')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistCompilata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('inizio', 'Inizio turno'), ('fine', 'Fine turno')], max_length=10)),
                ('esito', models.CharField(choices=[('ok', 'OK'), ('non_ok', 'Non OK'), ('na', 'N/A')], default='ok', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('compilato_il', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compilazioni', to='turni.checklistitem')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='turni.sessioneturno')),
            ],
            options={
                'verbose_name': 'Checklist compilata',
                'verbose_name_plural': 'Checklist compilate',
                'unique_together': {('sessione', 'checklist_item', 'fase')},
            },
        ),
    ]
