# Generated by Django 4.2.29 on 2026-04-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0002_crea_supplemento_sporco'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('icona', models.CharField(blank=True, default='', help_text='Classe Bootstrap icon, es. bi-wrench', max_length=50, verbose_name='Icona')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Categoria checklist',
                'verbose_name_plural': 'Categorie checklist',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['postazione_cq__ordine', 'blocco__ordine', 'categoria__ordine', 'ordine', 'nome'], 'verbose_name': 'Voce checklist', 'verbose_name_plural': 'Voci checklist'},
        ),
        migrations.CreateModel(
            name='EsitoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=30, verbose_name='Codice')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('colore', models.CharField(default='secondary', help_text='Classe Bootstrap: success, danger, warning, info, secondary', max_length=20, verbose_name='Colore')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esiti', to='turni.categoriachecklist')),
            ],
            options={
                'verbose_name': 'Esito checklist',
                'verbose_name_plural': 'Esiti checklist',
                'ordering': ['categoria__ordine', 'ordine'],
                'unique_together': {('categoria', 'codice')},
            },
        ),
        migrations.AddField(
            model_name='checklistcompilata',
            name='esito_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compilazioni', to='turni.esitochecklist', verbose_name='Esito (5S)'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='turni.categoriachecklist', verbose_name='Categoria 5S'),
        ),
    ]
