# Generated by Django 4.2.29 on 2026-04-15 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turni', '0004_seed_5s'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esito_verifica', models.CharField(choices=[('confermato', 'Confermato'), ('non_conforme', 'Non conforme')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('data_verifica', models.DateTimeField(auto_now_add=True)),
                ('compilata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifiche', to='turni.checklistcompilata')),
                ('verificato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifiche_checklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verifica checklist',
                'verbose_name_plural': 'Verifiche checklist',
                'ordering': ['-data_verifica'],
            },
        ),
    ]
