# Generated by Django 4.2.29 on 2026-04-16 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordini', '0008_add_priorita'),
        ('cq', '0009_popola_sigle'),
        ('turni', '0005_verifica_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegnalazioneDifetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=80, verbose_name='Zona auto')),
                ('tipo_difetto', models.CharField(max_length=80, verbose_name='Tipo difetto')),
                ('gravita', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segnalazioni_difetti', to=settings.AUTH_USER_MODEL)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni_difetti', to='ordini.ordine')),
                ('postazione_cq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cq.postazionecq')),
            ],
            options={
                'verbose_name': 'Segnalazione difetto',
                'verbose_name_plural': 'Segnalazioni difetti',
                'ordering': ['-data_ora'],
            },
        ),
    ]
