# Generated by Django 4.2.29 on 2026-04-16 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0009_popola_sigle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turni', '0006_segnalazione_difetto'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazionedifetto',
            name='azione',
            field=models.CharField(choices=[('corretto', 'Corretto prima della consegna'), ('segnalato', 'Solo segnalato (non corretto)')], default='corretto', max_length=20, verbose_name='Azione intrapresa'),
        ),
        migrations.AddField(
            model_name='segnalazionedifetto',
            name='postazione_produttore',
            field=models.CharField(blank=True, help_text='Codice della postazione responsabile del difetto', max_length=40, verbose_name='Postazione produttore'),
        ),
        migrations.AlterField(
            model_name='segnalazionedifetto',
            name='operatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segnalazioni_difetti', to=settings.AUTH_USER_MODEL, verbose_name='Rilevato da (operatore)'),
        ),
        migrations.AlterField(
            model_name='segnalazionedifetto',
            name='postazione_cq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cq.postazionecq', verbose_name='Rilevato da (postazione)'),
        ),
    ]
