# Generated by Django 4.2.29 on 2026-04-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0007_segnalazione_catena'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='in_apertura',
            field=models.BooleanField(default=True, help_text='Mostra questa voce nella checklist di inizio turno', verbose_name='In apertura turno'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='in_chiusura',
            field=models.BooleanField(default=True, help_text='Mostra questa voce nella checklist di fine turno', verbose_name='In chiusura turno'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Se impostato, questa voce e un subitem del padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='turni.checklistitem', verbose_name='Item padre'),
        ),
    ]
