# Generated by Django 4.2.29 on 2026-10-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0001_initial'),
        ('turni', '0008_checklist_subitems_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='assegnazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_checklist', to='magazzino.assegnazione'),
        ),
    ]
