# Generated by Django 4.2.29 on 2026-08-07 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0005_blocca_marketing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monete', '0007_alter_movimentomoneta_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio_iniziale', models.PositiveSmallIntegerField(default=50)),
                ('decadimento_giorni', models.PositiveSmallIntegerField(default=14, help_text='Ogni N giorni senza servizi il punteggio scende di decadimento_punti.')),
                ('decadimento_punti', models.PositiveSmallIntegerField(default=1)),
                ('soglia_notifica_salute', models.PositiveSmallIntegerField(default=60, help_text='Sotto questa soglia parte l\'evento di notifica "punteggio basso".')),
                ('streak_finestra_giorni', models.PositiveSmallIntegerField(default=21, help_text='La streak resta viva con almeno un servizio ogni N giorni.')),
                ('streak_traguardi', models.JSONField(default=dict, help_text='Mappa {servizi_consecutivi: gettoni}. Default: {"5": 1, "10": 3, "20": 6}.')),
                ('giorni_avviso_scadenza', models.JSONField(default=list, help_text='Giorni prima della scadenza trattamento a cui avvisare. Default: [30, 7].')),
                ('giorni_avviso_streak', models.PositiveSmallIntegerField(default=3, help_text='Avviso streak in scadenza N giorni prima.')),
                ('template_livello_completato', models.CharField(blank=True, default='', max_length=100)),
                ('template_badge_sbloccato', models.CharField(blank=True, default='', max_length=100)),
                ('template_salute_bassa', models.CharField(blank=True, default='', max_length=100)),
                ('template_streak_scadenza', models.CharField(blank=True, default='', max_length=100)),
                ('template_trattamento_scadenza', models.CharField(blank=True, default='', max_length=100)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni garage',
                'verbose_name_plural': 'Impostazioni garage',
            },
        ),
        migrations.CreateModel(
            name='Percorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('predefinito', models.BooleanField(default=False, help_text='Assegnato automaticamente ai nuovi veicoli. Deve essercene uno solo.')),
                ('attivo', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Percorso',
                'verbose_name_plural': 'Percorsi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServizioGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('punti_salute', models.PositiveSmallIntegerField(default=0, help_text='Punti aggiunti al punteggio salute (0-100).')),
                ('validita_giorni', models.PositiveSmallIntegerField(default=0, help_text='Durata del trattamento in giorni: alla scadenza risulta "da rinnovare". 0 = nessuna scadenza.')),
                ('badge_nome', models.CharField(blank=True, default='', help_text='Badge milestone sbloccato alla prima registrazione di questo servizio (vuoto = nessun badge).', max_length=100)),
                ('badge_icona', models.CharField(blank=True, default='bi-star', max_length=50)),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo servizio garage',
                'verbose_name_plural': 'Tipi servizio garage',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(help_text='Normalizzata maiuscola senza spazi.', max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=80)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='garage/veicoli/')),
                ('punteggio_salute', models.PositiveSmallIntegerField(default=50)),
                ('salute_aggiornata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('streak_conteggio', models.PositiveSmallIntegerField(default=0)),
                ('streak_iniziata_il', models.DateTimeField(blank=True, null=True)),
                ('streak_ultimo_evento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_uso_self', models.DateTimeField(blank=True, help_text="Per preselezionare il veicolo all'avvio self service.", null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veicoli', to='clienti.cliente')),
                ('percorso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veicoli', to='garage.percorso')),
            ],
            options={
                'verbose_name': 'Veicolo',
                'verbose_name_plural': 'Veicoli',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='PremioVeicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=80)),
                ('gettoni', models.PositiveSmallIntegerField()),
                ('descrizione', models.CharField(blank=True, default='', max_length=200)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('movimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monete.movimentomoneta')),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premi', to='garage.veicolo')),
            ],
            options={
                'verbose_name': 'Premio veicolo',
                'verbose_name_plural': 'Premi veicolo',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='NotificaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('livello_completato', 'Livello completato'), ('badge_sbloccato', 'Badge sbloccato'), ('salute_bassa', 'Punteggio sotto soglia'), ('streak_scadenza', 'Streak in scadenza'), ('trattamento_scadenza', 'Trattamento in scadenza')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('chiave_dedup', models.CharField(blank=True, default='', help_text='Evita doppi avvisi dal cron (es. "scadenza:coating:2027-01-15:30").', max_length=100)),
                ('inviata', models.BooleanField(default=False, help_text="True se il WhatsApp e' partito.")),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='garage.veicolo')),
            ],
            options={
                'verbose_name': 'Notifica garage',
                'verbose_name_plural': 'Notifiche garage',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='LivelloPercorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Ordine di sblocco: 1, 2, 3, 4...')),
                ('nome', models.CharField(max_length=100)),
                ('premio_gettoni', models.PositiveSmallIntegerField(default=0, help_text='Gettoni accreditati (una sola volta per veicolo) al completamento del livello.')),
                ('badge_nome', models.CharField(blank=True, default='', help_text='Badge di livello (vuoto = nessun badge).', max_length=100)),
                ('badge_icona', models.CharField(blank=True, default='bi-award', help_text='Classe Bootstrap Icons (es. bi-award).', max_length=50)),
                ('percorso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livelli', to='garage.percorso')),
            ],
            options={
                'verbose_name': 'Livello percorso',
                'verbose_name_plural': 'Livelli percorso',
                'ordering': ['percorso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemLivello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soddisfatto_da_self', models.BooleanField(default=False, help_text='Se attivo, anche un lavaggio self service completa questo item (es. lavaggio esterno).')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('livello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='garage.livellopercorso')),
                ('tipo_servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_livello', to='garage.tiposerviziogarage')),
            ],
            options={
                'verbose_name': 'Item livello',
                'verbose_name_plural': 'Item livello',
                'ordering': ['livello', 'ordine'],
            },
        ),
        migrations.CreateModel(
            name='EventoLibretto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(choices=[('self_service', 'Self service'), ('operatore', 'Operatore'), ('importato', 'Importato')], max_length=15)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='garage/eventi/')),
                ('codice_conferma', models.CharField(blank=True, default='', max_length=64)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('movimento', models.ForeignKey(blank=True, help_text="Movimento gettoni dell'avvio self service collegato.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monete.movimentomoneta')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='garage.tiposerviziogarage')),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='garage.veicolo')),
            ],
            options={
                'verbose_name': 'Evento libretto',
                'verbose_name_plural': 'Eventi libretto',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='BadgeVeicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('nome', models.CharField(max_length=100)),
                ('icona', models.CharField(default='bi-award', max_length=50)),
                ('ottenuto_il', models.DateTimeField(auto_now_add=True)),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='garage.veicolo')),
            ],
            options={
                'verbose_name': 'Badge veicolo',
                'verbose_name_plural': 'Badge veicolo',
                'ordering': ['ottenuto_il'],
            },
        ),
        migrations.AddConstraint(
            model_name='veicolo',
            constraint=models.UniqueConstraint(fields=('cliente', 'targa'), name='uq_veicolo_cliente_targa'),
        ),
        migrations.AddConstraint(
            model_name='premioveicolo',
            constraint=models.UniqueConstraint(fields=('veicolo', 'chiave'), name='uq_premio_veicolo_chiave'),
        ),
        migrations.AddConstraint(
            model_name='notificagarage',
            constraint=models.UniqueConstraint(condition=models.Q(('chiave_dedup', ''), _negated=True), fields=('veicolo', 'chiave_dedup'), name='uq_notifica_veicolo_dedup'),
        ),
        migrations.AddConstraint(
            model_name='livellopercorso',
            constraint=models.UniqueConstraint(fields=('percorso', 'numero'), name='uq_livello_percorso_numero'),
        ),
        migrations.AddConstraint(
            model_name='itemlivello',
            constraint=models.UniqueConstraint(fields=('livello', 'tipo_servizio'), name='uq_item_livello_tipo'),
        ),
        migrations.AddIndex(
            model_name='eventolibretto',
            index=models.Index(fields=['veicolo', '-data'], name='garage_even_veicolo_9a5c43_idx'),
        ),
        migrations.AddConstraint(
            model_name='badgeveicolo',
            constraint=models.UniqueConstraint(fields=('veicolo', 'slug'), name='uq_badge_veicolo_slug'),
        ),
    ]
