# Generated by Django 4.2.23 on 2025-07-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
                ('ordine_visualizzazione', models.IntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
                'ordering': ['ordine_visualizzazione', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Postazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
                ('attiva', models.BooleanField(default=True)),
                ('ordine_visualizzazione', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Postazioni',
                'ordering': ['ordine_visualizzazione', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Sconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('tipo_sconto', models.CharField(choices=[('percentuale', 'Percentuale'), ('importo', 'Importo Fisso')], max_length=20)),
                ('valore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sconti',
            },
        ),
        migrations.CreateModel(
            name='StampanteRete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('scontrino', 'Stampante Scontrini'), ('comanda', 'Stampante Comande'), ('report', 'Stampante Report')], max_length=20)),
                ('indirizzo_ip', models.GenericIPAddressField()),
                ('porta', models.IntegerField(default=9100)),
                ('modello', models.CharField(max_length=100)),
                ('larghezza_carta', models.IntegerField(default=80, help_text='Larghezza carta in mm')),
                ('attiva', models.BooleanField(default=True)),
                ('predefinita', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Stampanti di Rete',
                'unique_together': {('tipo', 'predefinita')},
            },
        ),
        migrations.CreateModel(
            name='ServizioProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('servizio', 'Servizio'), ('prodotto', 'Prodotto')], default='servizio', max_length=20)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField()),
                ('durata_minuti', models.IntegerField(default=30, help_text='Durata stimata in minuti (solo per servizi)')),
                ('quantita_disponibile', models.IntegerField(default=-1, help_text='-1 = illimitata (per servizi)')),
                ('quantita_minima_alert', models.IntegerField(default=5, help_text='Soglia per alert scorte basse')),
                ('codice_prodotto', models.CharField(blank=True, help_text='SKU/codice interno', max_length=50)),
                ('attivo', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('postazioni', models.ManyToManyField(blank=True, help_text='Postazioni che possono erogare questo servizio', to='core.postazione')),
            ],
            options={
                'verbose_name_plural': 'Servizi e Prodotti',
                'ordering': ['categoria__ordine_visualizzazione', 'titolo'],
            },
        ),
        migrations.AddField(
            model_name='postazione',
            name='stampante_comande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postazioni_comande', to='core.stampanterete'),
        ),
        migrations.CreateModel(
            name='MovimentoScorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carico', 'Carico'), ('scarico', 'Scarico'), ('rettifica', 'Rettifica Inventario')], max_length=20)),
                ('quantita', models.IntegerField(help_text='Positivo per carico, negativo per scarico')),
                ('quantita_prima', models.IntegerField()),
                ('quantita_dopo', models.IntegerField()),
                ('nota', models.TextField(blank=True)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servizioprodotto')),
            ],
            options={
                'verbose_name_plural': 'Movimenti Scorte',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
