# Generated by Django 4.2.23 on 2025-07-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ordini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoscorte',
            name='riferimento_ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordini.ordine'),
        ),
    ]
