# Generated by Django 4.2.29 on 2026-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='is_supplemento',
            field=models.BooleanField(default=False, help_text='Se attivo, disponibile come supplemento dalla dashboard operatore (es. sporco eccessivo)', verbose_name='Supplemento operatore'),
        ),
    ]
