# Generated by Django 4.2.29 on 2026-05-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prerequisiti_turni'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='mostra_pubblico',
            field=models.BooleanField(default=False, help_text='Se attivo, il servizio appare nel catalogo prenotabile dei clienti (/app/servizi/)', verbose_name='Mostra al pubblico (lato cliente)'),
        ),
    ]
