# Generated by Django 4.2.29 on 2026-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servizioprodotto_mostra_pubblico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='ordine_upsell',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordinamento nella sezione upsell (0 = primo). A parita' di ordine fallback su titolo."),
        ),
        migrations.AddField(
            model_name='servizioprodotto',
            name='proponi_in_upsell',
            field=models.BooleanField(default=False, help_text="Se attivo, l'item compare nella sezione 'Aggiungi extra' del riepilogo prenotazione online.", verbose_name='Proponi in upsell'),
        ),
        migrations.AddField(
            model_name='servizioprodotto',
            name='upsell_per',
            field=models.ManyToManyField(blank=True, help_text="Servizi base per cui questo item va proposto come upsell. Se vuoto, l'upsell e' universale (mostrato sempre). Se valorizzato, mostrato solo quando il cliente ha selezionato almeno uno dei servizi indicati.", limit_choices_to={'tipo': 'servizio'}, related_name='upsell_suggeriti', to='core.servizioprodotto'),
        ),
    ]
