# Generated by Django 4.2.29 on 2026-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_upsell_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='solo_pubblico',
            field=models.BooleanField(default=False, help_text="Se attivo, la categoria (e tutti i suoi item) viene mostrata SOLO nel catalogo della prenotazione online (/app/servizi/) e nascosta all'operatore in cassa (/ordini/cassa/). Utile per gestire cataloghi diversi tra cliente self-service e operatore al banco.", verbose_name='Solo prenotazione online'),
        ),
    ]
