# Generated by Django 4.2.29 on 2026-06-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoria_solo_pubblico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='categorie_aggiuntive',
            field=models.ManyToManyField(blank=True, help_text="Categorie extra in cui mostrare l'item, oltre alla categoria principale. Lascia vuoto se l'item appartiene a una sola categoria.", related_name='servizi_aggiuntivi', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='servizioprodotto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servizi_primari', to='core.categoria'),
        ),
    ]
