# Generated by Django 4.2.29 on 2026-06-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servizio_multicategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='selezione_singola',
            field=models.BooleanField(default=False, help_text="Se attivo, nel wizard di prenotazione online il cliente puo' scegliere UN solo servizio in questa categoria (comportamento radio button). Se disattivo, puo' selezionarne piu' di uno (comportamento checkbox, default). Usa singola per scelte alternative tipo 'Esterno base / Esterno completo / Esterno premium'.", verbose_name='Selezione singola nel wizard'),
        ),
    ]
