# Generated by Django 4.2.29 on 2026-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoria_selezione_singola'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='ordine_visualizzazione',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordinamento dell'item dentro la sua categoria (0 = primo, poi 1, 2, ...). A parita' di ordine, fallback su titolo alfabetico. L'ordine vale anche per le categorie aggiuntive."),
        ),
    ]
