# Generated by Django 4.2.29 on 2026-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servizio_ordine_visualizzazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='gruppo',
            field=models.CharField(blank=True, default='', help_text="Sotto-sezione opzionale dentro lo step del wizard. Item con lo stesso gruppo vengono raccolti sotto un'intestazione comune (es. 'Pelle' / 'Tessuto' dentro 'Trattamento sedili'). Lascia vuoto per item senza sotto-sezione. I gruppi sono ordinati alfabeticamente; per controllare l'ordine usa un prefisso numerico (es. '1. Pelle', '2. Tessuto').", max_length=100),
        ),
    ]
