# Generated by Django 4.2.29 on 2026-06-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servizio_gruppo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='ordine_gruppo',
            field=models.PositiveSmallIntegerField(default=0, help_text="Posizione del GRUPPO dentro lo step (0 = primo, poi 1, 2, ...). A parita' di ordine, fallback alfabetico sul nome del gruppo. Il save() lo propaga automaticamente a tutti gli item dello stesso gruppo+categoria, cosi' basta cambiarlo una volta per spostare l'intera sezione."),
        ),
        migrations.AlterField(
            model_name='servizioprodotto',
            name='gruppo',
            field=models.CharField(blank=True, default='', help_text="Sotto-sezione opzionale dentro lo step del wizard. Item con lo stesso gruppo vengono raccolti sotto un'intestazione comune (es. 'Pelle' / 'Tessuto' dentro 'Trattamento sedili'). Lascia vuoto per item senza sotto-sezione.", max_length=100),
        ),
    ]
