# Generated by Django 4.2.29 on 2026-10-08 14:59

from django.db import migrations, models


def prefill_programmi(apps, schema_editor):
    # Prefill dai titoli: completo a mano -> P5, altri completi ->
    # P4/P7/P8/P9. Correggibile poi dal catalogo.
    ServizioProdotto = apps.get_model('core', 'ServizioProdotto')
    for s in ServizioProdotto.objects.filter(
            tipo='servizio', titolo__icontains='lavaggio completo'):
        t = s.titolo.lower()
        s.programmi_portale = '5' if ('a mano' in t or 'manuale' in t) else '4,7,8,9'
        s.save(update_fields=['programmi_portale'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servizio_ordine_gruppo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioprodotto',
            name='programmi_portale',
            field=models.CharField(blank=True, default='', help_text="Programmi WashTec (1-9) con cui il portale esegue questo lavaggio, separati da virgola (es. '5' per il completo a mano, '4,7,8,9' per gli altri completi). Vuoto = non passa dal portale.", max_length=20, verbose_name='Programmi portale compatibili'),
        ),
        migrations.RunPython(prefill_programmi, migrations.RunPython.noop),
    ]
