# Generated by Django 4.2.29 on 2026-10-08 16:22

from django.db import migrations, models


def priorita_completi(apps, schema_editor):
    # I completi passano dall'ordine numerico all'ordine di priorita'
    # di abbinamento: prima P8, poi P9, P7 e infine P4.
    ServizioProdotto = apps.get_model('core', 'ServizioProdotto')
    ServizioProdotto.objects.filter(
        programmi_portale='4,7,8,9').update(programmi_portale='8,9,7,4')


def torna_numerico(apps, schema_editor):
    ServizioProdotto = apps.get_model('core', 'ServizioProdotto')
    ServizioProdotto.objects.filter(
        programmi_portale='8,9,7,4').update(programmi_portale='4,7,8,9')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servizioprodotto_programmi_portale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servizioprodotto',
            name='programmi_portale',
            field=models.CharField(blank=True, default='', help_text="Programmi WashTec (1-9) con cui il portale esegue questo lavaggio, separati da virgola IN ORDINE DI PRIORITA' di abbinamento (es. '5' per il completo a mano, '8,9,7,4' per gli altri completi: prima i P8, poi P9, P7 e infine P4). Vuoto = non passa dal portale.", max_length=20, verbose_name='Programmi portale compatibili'),
        ),
        migrations.RunPython(priorita_completi, torna_numerico),
    ]
