# Generated by Django 4.2.29 on 2026-10-10 15:20

from django.db import migrations, models


def ricariche_fuori_magazzino(apps, schema_editor):
    """Le ricariche credito (categoria "Credito Carte fedelta'") non sono merce."""
    apps.get_model('core', 'Categoria').objects.filter(nome__icontains='credito').update(senza_magazzino=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_programmi_portale_priorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='senza_magazzino',
            field=models.BooleanField(default=False, help_text='Se attivo, i prodotti di questa categoria (es. ricariche credito, buoni) non sono merce: non hanno un articolo nel Magazzino e non scaricano scorte.', verbose_name='Prodotti non di magazzino'),
        ),
        migrations.RunPython(ricariche_fuori_magazzino, migrations.RunPython.noop),
    ]
