# Generated by Django 4.2.23 on 2025-07-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0002_initial'),
        ('ordini', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioPersonalizzato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('chiuso', models.BooleanField(default=False)),
                ('orario_speciale_inizio', models.TimeField(blank=True, null=True)),
                ('orario_speciale_fine', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Calendario Personalizzato',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='SlotPrenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('prenotazioni_attuali', models.IntegerField(default=0)),
                ('max_prenotazioni', models.IntegerField()),
                ('disponibile', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Slot Prenotazioni',
                'ordering': ['data', 'ora_inizio'],
                'unique_together': {('data', 'ora_inizio')},
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata_stimata_minuti', models.IntegerField()),
                ('stato', models.CharField(choices=[('confermata', 'Confermata'), ('in_attesa', 'In Attesa'), ('completata', 'Completata'), ('annullata', 'Annullata'), ('no_show', 'No Show')], default='confermata', max_length=20)),
                ('codice_prenotazione', models.CharField(blank=True, max_length=10, unique=True)),
                ('nota_cliente', models.TextField(blank=True)),
                ('nota_interna', models.TextField(blank=True)),
                ('promemoria_inviato', models.BooleanField(default=False)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='clienti.cliente')),
                ('ordine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordini.ordine')),
                ('servizi', models.ManyToManyField(to='core.servizioprodotto')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='prenotazioni.slotprenotazione')),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['slot__data', 'slot__ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurazioneSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('durata_slot_minuti', models.IntegerField(default=30)),
                ('max_prenotazioni_per_slot', models.IntegerField(default=2)),
                ('attivo', models.BooleanField(default=True)),
                ('servizi_ammessi', models.ManyToManyField(blank=True, to='core.servizioprodotto')),
            ],
            options={
                'verbose_name_plural': 'Configurazioni Slot',
                'ordering': ['giorno_settimana', 'ora_inizio'],
                'unique_together': {('giorno_settimana', 'ora_inizio')},
            },
        ),
    ]
