# Generated by Django 4.2.23 on 2025-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='tipo_auto',
            field=models.CharField(blank=True, help_text="Modello e colore dell'auto", max_length=200),
        ),
    ]
