# Generated by Django 4.2.29 on 2026-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_remove_unique_constraint_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='email_contatto',
            field=models.EmailField(blank=True, default='', help_text='Email a cui inviare le notifiche di questa prenotazione', max_length=254),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='telefono_contatto',
            field=models.CharField(blank=True, default='', help_text='Telefono di contatto per questa prenotazione', max_length=20),
        ),
    ]
