# Generated by Django 4.2.29 on 2026-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0004_prenotazione_email_contatto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='proposta_inviata_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
