# Generated by Django 4.2.29 on 2026-06-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0005_prenotazione_proposta_inviata_il'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='ora_consegna_richiesta',
            field=models.TimeField(blank=True, help_text="Solo se tipo_consegna='programmata': orario al quale il cliente vuole ritirare", null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='tipo_consegna',
            field=models.CharField(choices=[('immediata', 'Consegna immediata'), ('programmata', 'Ritiro programmato')], default='immediata', help_text='immediata = consegna appena pronta; programmata = ritiro a un orario fisso', max_length=20),
        ),
    ]
