# Generated by Django 4.2.29 on 2026-06-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_upsell_flag'),
        ('prenotazioni', '0006_tipo_consegna'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveSmallIntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti_extra', to='prenotazioni.prenotazione')),
                ('servizio_prodotto', models.ForeignKey(limit_choices_to={'tipo': 'prodotto'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.servizioprodotto')),
            ],
            options={
                'verbose_name': 'Prodotto prenotazione',
                'verbose_name_plural': 'Prodotti prenotazione',
                'unique_together': {('prenotazione', 'servizio_prodotto')},
            },
        ),
    ]
