# Generated by Django 4.2.29 on 2026-07-11 15:20

from django.db import migrations, models
from django.db.models import Q


def backfill_origine(apps, schema_editor):
    """Le prenotazioni storiche non hanno il canale registrato.
    Euristica: solo il booking online valorizza email_contatto /
    telefono_contatto (la cassa non li compila mai) -> se almeno uno
    e' presente, la prenotazione e' arrivata dal web.
    """
    Prenotazione = apps.get_model('prenotazioni', 'Prenotazione')
    Prenotazione.objects.filter(
        Q(email_contatto__gt='') | Q(telefono_contatto__gt='')
    ).update(origine='web')


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0007_prenotazione_prodotto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='origine',
            field=models.CharField(choices=[('web', 'Prenotazione online'), ('cassa', 'Registrata in cassa')], default='cassa', max_length=10),
        ),
        migrations.RunPython(backfill_origine, migrations.RunPython.noop),
    ]
