# Generated by Django 4.2.23 on 2025-11-26 18:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiusuraCassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('data_ora_apertura', models.DateTimeField(auto_now_add=True)),
                ('fondo_cassa_iniziale', models.DecimalField(decimal_places=2, help_text="Contanti presenti all'apertura", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_ora_chiusura', models.DateTimeField(blank=True, null=True)),
                ('conteggio_cassa_reale', models.DecimalField(blank=True, decimal_places=2, help_text='Contanti effettivamente presenti alla chiusura', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('totale_incassi_contanti', models.DecimalField(decimal_places=2, default=0, help_text='Totale incassi in contanti della giornata', max_digits=10)),
                ('totale_pagamenti_contanti', models.DecimalField(decimal_places=2, default=0, help_text='Totale pagamenti in contanti (fornitori, spese)', max_digits=10)),
                ('totale_prelievi', models.DecimalField(decimal_places=2, default=0, help_text='Prelievi dal fondo cassa', max_digits=10)),
                ('totale_versamenti', models.DecimalField(decimal_places=2, default=0, help_text='Versamenti nel fondo cassa', max_digits=10)),
                ('totale_carte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale_bancomat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale_bonifici', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale_altro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note_apertura', models.TextField(blank=True)),
                ('note_chiusura', models.TextField(blank=True, help_text='Giustificazione differenze cassa')),
                ('stato', models.CharField(choices=[('aperta', 'Aperta'), ('chiusa', 'Chiusa')], default='aperta', max_length=20)),
                ('confermata', models.BooleanField(default=False, help_text='Chiusura confermata e bloccata')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('operatore_apertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperture_cassa', to=settings.AUTH_USER_MODEL)),
                ('operatore_chiusura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiusure_cassa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiusura Cassa',
                'verbose_name_plural': 'Chiusure Cassa',
                'ordering': ['-data'],
                'unique_together': {('data',)},
            },
        ),
        migrations.CreateModel(
            name='MovimentoCassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata'), ('uscita', 'Uscita'), ('prelievo', 'Prelievo'), ('versamento', 'Versamento')], max_length=20)),
                ('categoria', models.CharField(choices=[('pagamento', 'Pagamento Fornitore/Spesa'), ('prelievo_banca', 'Prelievo per Banca'), ('versamento_banca', 'Versamento da Banca'), ('fondo_cambio', 'Fondo Cambio'), ('altro', 'Altro')], max_length=30)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('causale', models.CharField(help_text='Descrizione del movimento', max_length=200)),
                ('dettagli', models.TextField(blank=True)),
                ('riferimento_documento', models.CharField(blank=True, help_text='Numero fattura, ricevuta, etc.', max_length=100)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('chiusura_cassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='finanze.chiusuracassa')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento Cassa',
                'verbose_name_plural': 'Movimenti Cassa',
                'ordering': ['-data_ora'],
            },
        ),
    ]
