# Generated by Django 4.2.29 on 2026-04-18 15:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('numero', models.CharField(blank=True, help_text='Numero identificativo della cassa (es. 11057)', max_length=20, verbose_name='Numero')),
                ('tipo', models.CharField(choices=[('servito', 'Servito (ordini POS)'), ('automatica', 'Cassa automatica')], max_length=20)),
                ('tracking_washcycles', models.BooleanField(default=False, help_text='Abilita il campo WashCycles nel form di chiusura', verbose_name='Traccia WashCycles')),
                ('attiva', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Cassa',
                'verbose_name_plural': 'Casse',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ChiusuraCassaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('data_ora_chiusura', models.DateTimeField(auto_now_add=True)),
                ('incasso_totale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Incasso totale')),
                ('incasso_ricarica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Incasso ricarica')),
                ('vendita_contante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Vendita contante')),
                ('vendita_non_contante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Vendita non contante')),
                ('resto_erogato_reale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conteggio reale del resto erogato (per verificare con il teorico)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Resto erogato reale (verifica fisica)')),
                ('wash_cycles', models.PositiveIntegerField(blank=True, help_text='Numero di cicli di lavaggio erogati (solo per i portali)', null=True, verbose_name='WashCycles')),
                ('note', models.TextField(blank=True)),
                ('confermata', models.BooleanField(default=False)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('cassa', models.ForeignKey(limit_choices_to={'tipo': 'automatica'}, on_delete=django.db.models.deletion.PROTECT, related_name='chiusure_automatiche', to='finanze.cassa')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiusure_automatiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiusura cassa automatica',
                'verbose_name_plural': 'Chiusure casse automatiche',
                'ordering': ['-data', 'cassa__ordine'],
                'unique_together': {('cassa', 'data')},
            },
        ),
    ]
