# Generated by Django 4.2.29 on 2026-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanze', '0003_seed_casse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassa',
            name='modalita_registratore',
            field=models.BooleanField(default=False, help_text='Se attivo, il form di chiusura mostra solo il totale scontrino (no vendite contante/non contante)', verbose_name='Modalita registratore (solo totale scontrino)'),
        ),
    ]
