# Generated by Django 4.2.29 on 2026-04-18 16:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanze', '0005_seed_registratore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiusuracassaautomatica',
            name='contanti_conteggiati',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somma fisica dei contanti presenti nella cassa a fine giornata', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Contanti conteggiati (fine giornata)'),
        ),
    ]
