# Generated by Django 4.2.29 on 2026-04-18 16:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanze', '0006_contanti_conteggiati'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadraturaGiornaliera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('contanti_totali', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Somma di tutto il contante scassettato dalle casse automatiche e dal registratore', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Contanti totali conteggiati')),
                ('lettore_carte_servito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Totale riportato dal terminale POS (lettore carte) del servito', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Totale lettore carte POS servito')),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadrature_giornaliere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quadratura giornaliera',
                'verbose_name_plural': 'Quadrature giornaliere',
                'ordering': ['-data'],
            },
        ),
    ]
