# Generated by Django 4.2.29 on 2026-04-20 10:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanze', '0007_quadratura_giornaliera'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadraturagiornaliera',
            name='fondo_cassa_iniziale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Contanti gia presenti in cassa all'inizio della giornata (verra sottratto dal totale reale)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Fondo cassa iniziale'),
        ),
    ]
