# Generated by Django 4.2.29 on 2026-10-07 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanze', '0008_quadraturagiornaliera_fondo_cassa_iniziale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransazionePortale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portale', models.CharField(choices=[('A', 'Portale A (serie 132xx)'), ('B', 'Portale B (serie 139xx)')], max_length=1)),
                ('numero', models.PositiveIntegerField(verbose_name='Numero transazione WashTec')),
                ('orario', models.DateTimeField(db_index=True)),
                ('programma', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('origine', models.CharField(choices=[('contanti', 'Contanti'), ('unita', "Unita' operativa")], max_length=10)),
                ('importato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transazione portale (WashTec)',
                'verbose_name_plural': 'Transazioni portali (WashTec)',
                'ordering': ['orario'],
                'unique_together': {('portale', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ChiusuraPortali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('periodo_da', models.DateTimeField(verbose_name='Inizio chiusura')),
                ('periodo_a', models.DateTimeField(verbose_name='Fine chiusura')),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiusure_portali', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiusura portali',
                'verbose_name_plural': 'Chiusure portali',
                'ordering': ['-data'],
            },
        ),
    ]
