# Generated by Django 4.2.29 on 2026-10-08 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0015_ordine_fattura_importo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanze', '0010_swap_origine_transazioni_portale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbbinamentoPortale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbinamenti_portale', to='ordini.itemordine')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abbinamenti_portale', to=settings.AUTH_USER_MODEL)),
                ('transazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abbinamento', to='finanze.transazioneportale')),
            ],
            options={
                'verbose_name': 'Abbinamento portale',
                'verbose_name_plural': 'Abbinamenti portale',
                'ordering': ['transazione__orario'],
            },
        ),
    ]
