# Generated by Django 4.2.29 on 2026-10-09 07:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanze', '0011_abbinamentoportale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpesaCassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descrizione', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('prodotti', 'Prodotti e materiali'), ('carburante', 'Carburante'), ('manutenzione', 'Manutenzione e riparazioni'), ('personale', 'Personale'), ('alimentari', 'Bar e alimentari'), ('altro', 'Altro')], default='altro', max_length=20)),
                ('riferimento', models.CharField(blank=True, help_text='Numero scontrino, fattura, ricevuta...', max_length=100)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_cassa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spesa pagata dalla cassa',
                'verbose_name_plural': 'Spese pagate dalla cassa',
                'ordering': ['data', 'creato_il'],
            },
        ),
    ]
