# Generated by Django 4.2.29 on 2026-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanze', '0012_spesacassa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transazioneportale',
            name='portale',
            field=models.CharField(choices=[('A', 'Portale Azzurro (A)'), ('B', 'Portale Blu (B)')], max_length=1),
        ),
    ]
