# Generated by Django 4.2.29 on 2026-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanze', '0013_portali_azzurro_blu'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiusuraportali',
            name='periodo_a_blu',
            field=models.DateTimeField(blank=True, help_text='Solo se diversa dalla fine generale', null=True, verbose_name='Fine chiusura Blu'),
        ),
        migrations.AddField(
            model_name='chiusuraportali',
            name='periodo_da_blu',
            field=models.DateTimeField(blank=True, help_text="Solo se diverso dall'inizio generale", null=True, verbose_name='Inizio chiusura Blu'),
        ),
    ]
