# Generated by Django 4.2.29 on 2026-10-10 18:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanze', '0014_chiusura_portali_orari_blu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RettificaResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('omaggio', 'Omaggio'), ('promo', 'Promo / sconto'), ('altro', 'Altro')], max_length=10)),
                ('importo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Incassato dagli operatori')),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rettifiche_residuo', to=settings.AUTH_USER_MODEL)),
                ('transazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rettifica_residuo', to='finanze.transazioneportale')),
            ],
            options={
                'verbose_name': 'Rettifica residuo portali',
                'verbose_name_plural': 'Rettifiche residuo portali',
            },
        ),
    ]
