# Generated by Django 4.2.29 on 2026-07-08 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0004_remove_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaggi', '0002_messaggiowhatsapp_media_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('manuale', 'Manuale'), ('automatica_richiamo', 'Richiamo automatico')], default='manuale', max_length=30)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('in_coda', 'In coda'), ('in_corso', 'In corso'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='bozza', max_length=20)),
                ('template_meta', models.CharField(help_text="Nome del template Meta approvato da usare per l'invio.", max_length=100)),
                ('template_params', models.JSONField(blank=True, default=list, help_text='Parametri body del template in ordine. Placeholder supportati: {nome}, {giorni_ultimo_lavaggio}, {totale_lavaggi}. Esempio: ["{nome}", "20%"]')),
                ('segmento_origine', models.CharField(blank=True, default='', help_text="Segmento da cui e' partita la selezione (informativo).", max_length=30)),
                ('finestra_conversione_giorni', models.PositiveSmallIntegerField(default=21, help_text='Copia della finestra conversione al momento del lancio.')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('lanciata_il', models.DateTimeField(blank=True, null=True)),
                ('completata_il', models.DateTimeField(blank=True, null=True)),
                ('creata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagna',
                'verbose_name_plural': 'Campagne',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='ImpostazioniMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorni_dormiente', models.PositiveSmallIntegerField(default=120, help_text="Nessun lavaggio da piu' di N giorni -> cliente 'dormiente'.")),
                ('giorni_rallentamento_delta', models.PositiveSmallIntegerField(default=30, help_text="Se i giorni dall'ultimo lavaggio superano la frequenza media del cliente + questo delta -> 'in rallentamento'.")),
                ('max_invii_giorno', models.PositiveSmallIntegerField(default=40, help_text='Tetto massimo di messaggi promozionali inviabili in un giorno (tutte le campagne sommate). Protegge il numero WhatsApp Business da blocchi anti-spam Meta.')),
                ('intervallo_min_secondi', models.PositiveSmallIntegerField(default=45, help_text='Pausa minima tra due invii consecutivi (secondi).')),
                ('intervallo_max_secondi', models.PositiveSmallIntegerField(default=180, help_text="Pausa massima tra due invii consecutivi (secondi). La pausa effettiva e' un valore casuale nel range.")),
                ('finestra_no_ricontatto_giorni', models.PositiveSmallIntegerField(default=30, help_text='Un cliente che ha ricevuto un messaggio promozionale negli ultimi N giorni non viene ricontattato.')),
                ('richiamo_automatico_attivo', models.BooleanField(default=False, help_text='Interruttore ON/OFF del richiamo automatico post-lavaggio.')),
                ('richiamo_giorni_dopo', models.PositiveSmallIntegerField(default=45, help_text="Invia il promemoria quando l'ultimo lavaggio risale a N giorni fa.")),
                ('richiamo_template_meta', models.CharField(blank=True, default='', help_text="Nome del template Meta approvato per il richiamo automatico (es. 'richiamo_45_giorni'). Vuoto = richiamo disattivato anche se l'interruttore e' ON.", max_length=100)),
                ('giorni_finestra_conversione', models.PositiveSmallIntegerField(default=21, help_text="Un cliente 'converte' se torna a lavare entro N giorni dal messaggio.")),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni marketing',
                'verbose_name_plural': 'Impostazioni marketing',
            },
        ),
        migrations.CreateModel(
            name='InvioCampagna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('in_coda', 'In coda'), ('inviato', 'Inviato'), ('fallito', 'Fallito'), ('saltato', 'Saltato')], default='in_coda', max_length=12)),
                ('inviato_il', models.DateTimeField(blank=True, null=True)),
                ('motivo_salto', models.CharField(blank=True, default='', help_text="Perche' l'invio e' stato saltato (opt-out, no telefono, gia' contattato di recente, ...).", max_length=200)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('campagna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invii', to='marketing.campagna')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invii_marketing', to='clienti.cliente')),
                ('messaggio_wa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaggi.messaggiowhatsapp')),
            ],
            options={
                'verbose_name': 'Invio campagna',
                'verbose_name_plural': 'Invii campagna',
                'indexes': [models.Index(fields=['stato', 'campagna'], name='marketing_i_stato_9a6d6e_idx'), models.Index(fields=['cliente', 'inviato_il'], name='marketing_i_cliente_bfe271_idx')],
                'unique_together': {('campagna', 'cliente')},
            },
        ),
    ]
