# Generated by Django 4.2.29 on 2026-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagna',
            name='segmento_origine',
            field=models.CharField(blank=True, default='', help_text="Segmenti da cui e' partita la selezione (informativo). Piu' segmenti sono separati da virgola; 'tutti' = intera anagrafica.", max_length=120),
        ),
    ]
