# Generated by Django 4.2.29 on 2026-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_segmento_origine_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagna',
            name='stato',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('in_coda', 'In coda'), ('in_corso', 'In corso'), ('in_pausa', 'In pausa'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='bozza', max_length=20),
        ),
    ]
