# Generated by Django 4.2.29 on 2026-07-14 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_campagna_in_pausa'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionimarketing',
            name='orario_invio_a',
            field=models.TimeField(default=datetime.time(20, 0), help_text="La coda smette di inviare dopo quest'ora. Il bottone 'Invia ora' per singolo destinatario ignora la fascia (scelta esplicita dell'operatore)."),
        ),
        migrations.AddField(
            model_name='impostazionimarketing',
            name='orario_invio_da',
            field=models.TimeField(default=datetime.time(9, 0), help_text="La coda invia messaggi promozionali solo a partire da quest'ora (ora locale)."),
        ),
    ]
