# Generated by Django 4.2.29 on 2026-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_impostazionimarketing_orario_invio_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoPersonalizzato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.CharField(blank=True, default='', max_length=200)),
                ('attivo', models.BooleanField(default=True)),
                ('lavaggi_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Totale lavaggi (min)')),
                ('lavaggi_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Totale lavaggi (max)')),
                ('giorni_ultimo_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Giorni da ultimo lavaggio (min)')),
                ('giorni_ultimo_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Giorni da ultimo lavaggio (max)')),
                ('frequenza_min', models.FloatField(blank=True, help_text='Clienti che tornano ogni ALMENO N giorni. I clienti con 1 solo lavaggio sono esclusi dai filtri frequenza.', null=True, verbose_name='Frequenza media gg (min)')),
                ('frequenza_max', models.FloatField(blank=True, help_text='Clienti che tornano ogni AL MASSIMO N giorni (frequenti). Es. max 30 = almeno un lavaggio al mese.', null=True, verbose_name='Frequenza media gg (max)')),
                ('spesa_totale_min', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Spesa totale EUR (min)')),
                ('spesa_totale_max', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Spesa totale EUR (max)')),
                ('spesa_media_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Spesa media a lavaggio EUR (min)')),
                ('spesa_media_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Spesa media a lavaggio EUR (max)')),
                ('tipo_cliente', models.CharField(blank=True, choices=[('', 'Tutti'), ('privato', 'Solo privati'), ('azienda', 'Solo aziende')], default='', max_length=10)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segmento personalizzato',
                'verbose_name_plural': 'Segmenti personalizzati',
                'ordering': ['nome'],
            },
        ),
    ]
