# Generated by Django 4.2.29 on 2026-07-30 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0005_segmentopersonalizzato'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisiAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('modello', models.CharField(default='', help_text='Modello Claude usato per questa analisi.', max_length=60)),
                ('contesto', models.JSONField(default=dict)),
                ('analisi', models.TextField(default='', help_text="Analisi generale dell'andamento marketing.")),
                ('best_practice', models.JSONField(default=list)),
                ('proposte_segmenti', models.JSONField(default=list)),
                ('proposte_campagne', models.JSONField(default=list)),
                ('promozioni', models.JSONField(default=list)),
                ('token_input', models.PositiveIntegerField(default=0)),
                ('token_output', models.PositiveIntegerField(default=0)),
                ('creata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analisi AI',
                'verbose_name_plural': 'Analisi AI',
                'ordering': ['-creata_il'],
            },
        ),
    ]
