# Generated by Django 4.2.29 on 2026-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_analisiai'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisiai',
            name='proposte_template',
            field=models.JSONField(default=list, help_text='Bozze di template WhatsApp da creare/approvare su Meta.'),
        ),
    ]
