# Generated by Django 4.2.29 on 2026-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_analisiai_proposte_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagna',
            name='flusso_continuo',
            field=models.BooleanField(default=False, help_text='Il cron riaccoda automaticamente i nuovi clienti che entrano nei segmenti della campagna.'),
        ),
        migrations.AddField(
            model_name='campagna',
            name='riaggancio_giorni',
            field=models.PositiveSmallIntegerField(default=0, help_text="Solo flusso continuo: dopo N giorni dall'invio, un cliente che rientra nel segmento puo' essere ricontattato da questa campagna. 0 = mai (ogni cliente riceve al massimo un messaggio)."),
        ),
    ]
