# Generated by Django 4.2.29 on 2026-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_campagna_flusso_continuo_campagna_riaggancio_giorni'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionimarketing',
            name='telefono_test',
            field=models.CharField(blank=True, default='', help_text='Numero WhatsApp (es. 3791234567) a cui inviare i messaggi di prova dal composer campagne. Di solito il numero del titolare.', max_length=20),
        ),
    ]
