# Generated by Django 4.2.29 on 2026-04-09 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordini', '0004_ordine_durata_modificata_manualmente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifettoCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('carrozzeria_aloni_residui', 'Carrozzeria — aloni / gocce / residui'), ('parabrezza_esterno', 'Parabrezza esterno'), ('lunotto_esterno', 'Lunotto esterno'), ('vetri_laterali_esterni', 'Vetri laterali esterni'), ('specchietti_esterni', 'Specchietti esterni sx e dx'), ('cerchi', 'Cerchi'), ('passaruota', 'Passaruota'), ('gomme_nero_gomme', 'Gomme — nero gomme'), ('paraurti', 'Paraurti anteriore e posteriore'), ('cruscotto_plancia', 'Cruscotto e plancia'), ('bocchette_aria', 'Bocchette aria'), ('tunnel_centrale', 'Tunnel centrale'), ('montanti', 'Montanti'), ('battitacchi', 'Battitacchi'), ('sedile_guidatore', 'Sedile guidatore'), ('sedile_passeggero', 'Sedile passeggero'), ('sedili_posteriori', 'Sedili posteriori'), ('vani_portiere', 'Vani portiere'), ('pannelli_portiere', 'Pannelli portiere'), ('moquette_ant_sx', 'Moquette anteriore sx'), ('moquette_ant_dx', 'Moquette anteriore dx'), ('moquette_post_sx', 'Moquette posteriore sx'), ('moquette_post_dx', 'Moquette posteriore dx'), ('tappeto_guidatore', 'Tappeto guidatore'), ('tappeto_passeggero', 'Tappeto passeggero'), ('parabrezza_interno', 'Parabrezza interno'), ('lunotto_interno', 'Lunotto interno'), ('vetri_laterali_interni', 'Vetri laterali interni'), ('specchietto_retrovisore_int', 'Specchietto retrovisore interno'), ('parasoli', 'Parasoli'), ('cofano_interno', 'Cofano interno'), ('bagagliaio', 'Bagagliaio'), ('cassetto_guanti', 'Cassetto guanti')], max_length=40, verbose_name='Zona auto')),
                ('tipo_difetto', models.CharField(choices=[('briciole_sabbia_polvere', 'Briciole / sabbia / polvere'), ('fango', 'Fango'), ('macchia_organica', 'Macchia organica'), ('escrementi_insetti', 'Escrementi / insetti'), ('alone_vetro', 'Alone su vetro'), ('alone_plastica', 'Alone su plastica'), ('prodotto_non_rimosso', 'Prodotto non rimosso'), ('nero_gomme_non_uniforme', 'Nero gomme non uniforme'), ('zona_non_trattata', 'Zona non trattata'), ('profumo_non_applicato', 'Profumo non applicato'), ('foglio_protettivo_mancante', 'Foglio protettivo mancante'), ('nero_gomme_mancante', 'Nero gomme mancante'), ('graffio_carrozzeria', 'Graffio carrozzeria'), ('graffio_plastica', 'Graffio plastica interna'), ('altro', 'Altro')], max_length=30, verbose_name='Tipo di difetto')),
                ('descrizione_altro', models.CharField(blank=True, max_length=255, verbose_name='Descrizione (se Altro)')),
                ('gravita', models.CharField(choices=[('bassa', 'Bassa — imperfezione minore'), ('media', 'Media — difetto al controllo interno'), ('alta', 'Alta — cliente insoddisfatto / danno')], max_length=10, verbose_name='Gravità')),
                ('postazione_responsabile', models.CharField(choices=[('post1', 'Postazione 1 — Pre-lavaggio'), ('post2', 'Postazione 2 — Spazzole'), ('post3', 'Postazione 3 — Aspirazione'), ('post4', 'Postazione 4 — Plastiche e vetri'), ('controllo_finale', 'Controllo finale')], max_length=20, verbose_name='Postazione responsabile')),
                ('azione_correttiva', models.CharField(choices=[('sistemato', 'Sistemato prima della consegna'), ('cliente_informato', 'Cliente informato al momento della consegna'), ('da_richiamare', 'Cliente già consegnato — da richiamare'), ('danno_titolare', 'Danno — verificare con il titolare')], max_length=20, verbose_name='Azione correttiva')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cq/foto/', verbose_name='Foto')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Difetto CQ',
                'verbose_name_plural': 'Difetti CQ',
            },
        ),
        migrations.CreateModel(
            name='SchedaCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rilevato_da', models.CharField(choices=[('responsabile', 'Responsabile'), ('vice', 'Vice (in sostituzione del responsabile)'), ('cliente', 'Cliente'), ('titolare', 'Titolare (controllo a campione)')], max_length=20, verbose_name='Rilevato da')),
                ('esito', models.CharField(choices=[('ok', 'OK — nessun difetto'), ('non_ok', 'Non OK — difetti rilevati')], max_length=10, verbose_name='Esito')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='Note aggiuntive')),
                ('stato', models.CharField(choices=[('aperta', 'Aperta (modificabile)'), ('chiusa', 'Chiusa (definitiva)')], default='aperta', max_length=10, verbose_name='Stato scheda')),
                ('compilata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schede_cq_compilate', to=settings.AUTH_USER_MODEL, verbose_name='Compilata da')),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheda_cq', to='ordini.ordine')),
            ],
            options={
                'verbose_name': 'Scheda CQ',
                'verbose_name_plural': 'Schede CQ',
                'ordering': ['-data_ora'],
            },
        ),
        migrations.CreateModel(
            name='PunteggioCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punti', models.IntegerField()),
                ('tipo', models.CharField(choices=[('positivo', 'Positivo (CQ senza difetti)'), ('negativo_produttore', 'Negativo — produttore del difetto'), ('negativo_catena', 'Negativo — catena (non ha intercettato)'), ('negativo_responsabile', 'Negativo — controllo finale fallito'), ('modifica_titolare', 'Modifica manuale titolare')], max_length=30)),
                ('mese', models.PositiveSmallIntegerField()),
                ('anno', models.PositiveSmallIntegerField()),
                ('motivazione', models.TextField(blank=True)),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('difetto', models.ForeignKey(blank=True, help_text='Null se punteggio positivo (CQ OK)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punteggi', to='cq.difettocq')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punteggi_cq', to=settings.AUTH_USER_MODEL)),
                ('scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punteggi', to='cq.schedacq')),
            ],
            options={
                'verbose_name': 'Punteggio CQ',
                'verbose_name_plural': 'Punteggi CQ',
                'ordering': ['-data_ora'],
            },
        ),
        migrations.CreateModel(
            name='ModificaPunteggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField()),
                ('mese', models.PositiveSmallIntegerField()),
                ('punti', models.IntegerField(help_text='Valore positivo o negativo')),
                ('motivazione', models.TextField(verbose_name='Motivazione (obbligatoria)')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifiche_punteggio_create', to=settings.AUTH_USER_MODEL)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifiche_punteggio_ricevute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modifica punteggio',
                'verbose_name_plural': 'Modifiche punteggio',
                'ordering': ['-data_ora'],
            },
        ),
        migrations.AddField(
            model_name='difettocq',
            name='scheda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difetti', to='cq.schedacq'),
        ),
        migrations.CreateModel(
            name='OperatorePostazioneTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postazione', models.CharField(choices=[('post1', 'Postazione 1 — Pre-lavaggio'), ('post2', 'Postazione 2 — Spazzole'), ('post3', 'Postazione 3 — Aspirazione'), ('post4', 'Postazione 4 — Plastiche e vetri'), ('controllo_finale', 'Controllo finale')], max_length=20)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turni_postazione', to=settings.AUTH_USER_MODEL)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatori_turno', to='ordini.ordine')),
            ],
            options={
                'verbose_name': 'Operatore in turno',
                'verbose_name_plural': 'Operatori in turno',
                'ordering': ['ordine', 'postazione'],
                'unique_together': {('ordine', 'postazione', 'operatore')},
            },
        ),
        migrations.CreateModel(
            name='ImpostazionePremioMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField()),
                ('mese', models.PositiveSmallIntegerField()),
                ('monte_premi', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monte premi (€)')),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('validato', models.BooleanField(default=False, help_text='Il titolare ha congelato il mese')),
                ('validato_il', models.DateTimeField(blank=True, null=True)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impostazioni_premio_create', to=settings.AUTH_USER_MODEL)),
                ('validato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premi_validati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impostazione premio mensile',
                'verbose_name_plural': 'Impostazioni premio mensile',
                'ordering': ['-anno', '-mese'],
                'unique_together': {('anno', 'mese')},
            },
        ),
    ]
