# Generated by Django 4.2.29 on 2026-04-14 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0004_ordine_durata_modificata_manualmente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cq', '0004_popola_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostazioneCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=20, unique=True, verbose_name='Codice')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('is_controllo_finale', models.BooleanField(default=False, help_text='Segna questa postazione come controllo finale (una sola)', verbose_name='Controllo finale')),
            ],
            options={
                'verbose_name': 'Postazione CQ',
                'verbose_name_plural': 'Postazioni CQ',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='operatorepostazioneturno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='operatorepostazioneturno',
            name='blocco_codice',
            field=models.CharField(blank=True, default='', help_text='Vuoto = intera postazione', max_length=40, verbose_name='Blocco'),
        ),
        migrations.AlterField(
            model_name='difettocq',
            name='postazione_responsabile',
            field=models.CharField(max_length=20, verbose_name='Postazione responsabile'),
        ),
        migrations.AlterField(
            model_name='operatorepostazioneturno',
            name='postazione',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipodifettoconfig',
            name='richiede_descrizione',
            field=models.BooleanField(default=False, help_text='Se attivo, mostra un campo testo libero', verbose_name='Richiede descrizione'),
        ),
        migrations.AlterField(
            model_name='zonaconfig',
            name='postazione_produttore',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postazione produttore'),
        ),
        migrations.AlterField(
            model_name='zonaconfig',
            name='postazioni_catena',
            field=models.JSONField(blank=True, default=list, help_text='Postazioni intermedie che avrebbero dovuto intercettare il difetto', verbose_name='Postazioni catena'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorepostazioneturno',
            unique_together={('ordine', 'postazione', 'blocco_codice', 'operatore')},
        ),
        migrations.CreateModel(
            name='ConfigurazioneAssegnazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurazioni_assegnazione_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurazione assegnazione',
                'verbose_name_plural': 'Configurazioni assegnazione',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BloccoPostazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=40, unique=True, verbose_name='Codice')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocchi', to='cq.postazionecq', verbose_name='Postazione')),
            ],
            options={
                'verbose_name': 'Blocco postazione',
                'verbose_name_plural': 'Blocchi postazione',
                'ordering': ['ordine', 'nome'],
                'unique_together': {('postazione', 'codice')},
            },
        ),
        migrations.CreateModel(
            name='AssegnazionePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postazione_codice', models.CharField(max_length=20, verbose_name='Postazione')),
                ('blocco_codice', models.CharField(blank=True, default='', help_text='Vuoto = intera postazione', max_length=40, verbose_name='Blocco')),
                ('configurazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='cq.configurazioneassegnazione')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_preset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assegnazione preset',
                'verbose_name_plural': 'Assegnazioni preset',
                'unique_together': {('configurazione', 'postazione_codice', 'blocco_codice', 'operatore')},
            },
        ),
    ]
