# Generated by Django 4.2.29 on 2026-04-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prerequisiti_turni'),
        ('cq', '0006_popola_postazioni_cq'),
    ]

    operations = [
        migrations.AddField(
            model_name='postazionecq',
            name='postazione_fisica',
            field=models.ForeignKey(blank=True, help_text='Collega alla postazione fisica per il routing ordini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postazione_cq', to='core.postazione', verbose_name='Postazione fisica collegata'),
        ),
    ]
