# Generated by Django 4.2.29 on 2026-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0007_prerequisiti_turni'),
    ]

    operations = [
        migrations.AddField(
            model_name='postazionecq',
            name='sigla',
            field=models.CharField(blank=True, default='', help_text='Sigla breve per i bollini (es. PL, SP, AS, PV, CF)', max_length=5, verbose_name='Sigla'),
        ),
    ]
