# Generated by Django 4.2.29 on 2026-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0009_popola_sigle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedacq',
            name='esito',
            field=models.CharField(choices=[('ok', 'OK — nessun difetto'), ('ok_con_rilievo', 'OK — con rilievo (intercettato e corretto)'), ('non_ok', 'Non OK — difetto rilevato in uscita')], max_length=20, verbose_name='Esito'),
        ),
    ]
