# Generated by Django 4.2.29 on 2026-10-10 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermessoUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[('clienti', 'Clienti'), ('messaggi', 'Messaggi WhatsApp'), ('cassa', 'Cassa'), ('ordini', 'Ordini'), ('task', 'Task'), ('marketing', 'Marketing'), ('fatture', 'Fatture'), ('abbonamenti', 'Abbonamenti'), ('prenotazioni', 'Prenotazioni'), ('qualita', 'Qualità'), ('mio_turno', 'Il Mio Turno'), ('report_turni', 'Turni (report)'), ('finanze', 'Finanze'), ('monete', 'Monete'), ('configurazione', 'Configurazione'), ('permessi', 'Permessi')], max_length=30)),
                ('consenti', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permessi_sezione', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eccezione per utente',
                'verbose_name_plural': 'Eccezioni per utente',
                'unique_together': {('sezione', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PermessoGruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[('clienti', 'Clienti'), ('messaggi', 'Messaggi WhatsApp'), ('cassa', 'Cassa'), ('ordini', 'Ordini'), ('task', 'Task'), ('marketing', 'Marketing'), ('fatture', 'Fatture'), ('abbonamenti', 'Abbonamenti'), ('prenotazioni', 'Prenotazioni'), ('qualita', 'Qualità'), ('mio_turno', 'Il Mio Turno'), ('report_turni', 'Turni (report)'), ('finanze', 'Finanze'), ('monete', 'Monete'), ('configurazione', 'Configurazione'), ('permessi', 'Permessi')], max_length=30)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permessi_sezione', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permesso di gruppo',
                'verbose_name_plural': 'Permessi di gruppo',
                'unique_together': {('sezione', 'gruppo')},
            },
        ),
    ]
