# Generated by Django 4.2.29 on 2026-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_permessi_iniziali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permessogruppo',
            name='sezione',
            field=models.CharField(choices=[('clienti', 'Clienti'), ('messaggi', 'Messaggi WhatsApp'), ('cassa', 'Cassa'), ('ordini', 'Ordini'), ('task', 'Task'), ('marketing', 'Marketing'), ('fatture', 'Fatture'), ('abbonamenti', 'Abbonamenti'), ('prenotazioni', 'Prenotazioni'), ('qualita', 'Qualità'), ('mio_turno', 'Il Mio Turno'), ('report_turni', 'Turni (report)'), ('magazzino', 'Magazzino'), ('finanze', 'Finanze'), ('monete', 'Monete'), ('configurazione', 'Configurazione'), ('permessi', 'Permessi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='permessoutente',
            name='sezione',
            field=models.CharField(choices=[('clienti', 'Clienti'), ('messaggi', 'Messaggi WhatsApp'), ('cassa', 'Cassa'), ('ordini', 'Ordini'), ('task', 'Task'), ('marketing', 'Marketing'), ('fatture', 'Fatture'), ('abbonamenti', 'Abbonamenti'), ('prenotazioni', 'Prenotazioni'), ('qualita', 'Qualità'), ('mio_turno', 'Il Mio Turno'), ('report_turni', 'Turni (report)'), ('magazzino', 'Magazzino'), ('finanze', 'Finanze'), ('monete', 'Monete'), ('configurazione', 'Configurazione'), ('permessi', 'Permessi')], max_length=30),
        ),
    ]
