# Generated by Django 4.2.23 on 2025-07-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clienti', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_progressivo', models.CharField(blank=True, max_length=20, unique=True)),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('origine', models.CharField(choices=[('operatore', 'Operatore'), ('online', 'Online'), ('app', 'App Mobile'), ('totem', 'Totem Self-Service'), ('prenotazione', 'Prenotazione Web'), ('shop', 'Shop Online'), ('abbonamento', 'Abbonamento')], default='operatore', max_length=20)),
                ('tipo_consegna', models.CharField(choices=[('immediata', 'Consegna Immediata'), ('programmata', 'Consegna Programmata')], default='immediata', max_length=20)),
                ('ora_consegna_richiesta', models.TimeField(blank=True, null=True)),
                ('ora_consegna_prevista', models.DateTimeField(blank=True, null=True)),
                ('tempo_attesa_minuti', models.IntegerField(default=0)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importo_sconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale_finale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('punti_fedelta_generati', models.IntegerField(default=0)),
                ('stato_pagamento', models.CharField(choices=[('pagato', 'Pagato'), ('non_pagato', 'Non Pagato'), ('parziale', 'Pagamento Parziale'), ('differito', 'Pagamento Differito')], default='non_pagato', max_length=20)),
                ('importo_pagato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50)),
                ('data_scadenza_pagamento', models.DateField(blank=True, null=True)),
                ('nota', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('nuovo', 'Nuovo'), ('in_lavorazione', 'In Lavorazione'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='nuovo', max_length=20)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clienti.cliente')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sconto_applicato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sconto')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_ora'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('contanti', 'Contanti'), ('carta', 'Carta di Credito/Debito'), ('bancomat', 'Bancomat'), ('bonifico', 'Bonifico'), ('assegno', 'Assegno'), ('abbonamento', 'Abbonamento')], max_length=20)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('riferimento', models.CharField(blank=True, help_text='Num. transazione, assegno, etc.', max_length=100)),
                ('nota', models.TextField(blank=True)),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='ordini.ordine')),
            ],
            options={
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('in_lavorazione', 'In Lavorazione'), ('completato', 'Completato')], default='in_attesa', max_length=20)),
                ('inizio_lavorazione', models.DateTimeField(blank=True, null=True)),
                ('fine_lavorazione', models.DateTimeField(blank=True, null=True)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordini.ordine')),
                ('postazione_assegnata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postazione')),
                ('servizio_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servizioprodotto')),
            ],
            options={
                'verbose_name_plural': 'Item Ordine',
                'ordering': ['postazione_assegnata', 'id'],
            },
        ),
    ]
