# Generated by Django 4.2.23 on 2025-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='tipo_auto',
            field=models.CharField(blank=True, help_text="Modello e colore dell'auto", max_length=200),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=models.CharField(choices=[('in_attesa', 'In Attesa'), ('in_lavorazione', 'In Lavorazione'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='in_attesa', max_length=20),
        ),
    ]
