# Generated by Django 4.2.29 on 2026-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0002_ordine_tipo_auto_alter_ordine_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='auto_ritirata',
            field=models.BooleanField(default=False, help_text="Indica se l'auto è stata ritirata dal cliente"),
        ),
        migrations.AddField(
            model_name='ordine',
            name='data_ritiro',
            field=models.DateTimeField(blank=True, help_text='Data e ora del ritiro', null=True),
        ),
    ]
