# Generated by Django 4.2.29 on 2026-03-09 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordini', '0003_ordine_auto_ritirata_ordine_data_ritiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='durata_modificata_manualmente',
            field=models.BooleanField(default=False, help_text="True se l'operatore ha modificato manualmente la durata"),
        ),
        migrations.AddField(
            model_name='ordine',
            name='durata_stimata_minuti',
            field=models.IntegerField(default=0, help_text="Durata totale stimata per completare l'ordine (calcolata o modificata manualmente)"),
        ),
        migrations.CreateModel(
            name='ConfigurazionePianificazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_inizio', models.TimeField(default=datetime.time(8, 0))),
                ('ora_fine', models.TimeField(default=datetime.time(19, 0))),
                ('pausa_pranzo_attiva', models.BooleanField(default=True)),
                ('ora_inizio_pausa', models.TimeField(default=datetime.time(13, 0))),
                ('ora_fine_pausa', models.TimeField(default=datetime.time(15, 0))),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('aggiornato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurazione Pianificazione',
                'verbose_name_plural': 'Configurazione Pianificazione',
            },
        ),
    ]
