# Generated by Django 4.2.29 on 2026-04-15 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordini', '0004_ordine_durata_modificata_manualmente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordine',
            name='aggiunto_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_aggiunti', to=settings.AUTH_USER_MODEL, verbose_name='Aggiunto da operatore'),
        ),
    ]
