# Generated by Django 4.2.29 on 2026-04-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0007_prerequisiti_turni'),
        ('ordini', '0005_aggiunto_da_operatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordine',
            name='postazione_cq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_ordine', to='cq.postazionecq', verbose_name='Postazione CQ'),
        ),
    ]
