# Generated by Django 4.2.29 on 2026-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0007_popola_postazione_cq'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='priorita',
            field=models.IntegerField(default=0, help_text='Ordine di priorità: valori più bassi = priorità più alta. 0 = automatico.', verbose_name='Priorità lavorazione'),
        ),
    ]
