# Generated by Django 4.2.29 on 2026-05-05 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_prerequisiti_turni'),
        ('ordini', '0008_add_priorita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPreferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('servizio_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferiti_per_user', to='core.servizioprodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_preferiti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item preferito',
                'verbose_name_plural': 'Items preferiti',
                'ordering': ['-creato_il'],
                'unique_together': {('user', 'servizio_prodotto')},
            },
        ),
    ]
