# Generated by Django 4.2.29 on 2026-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0009_itempreferito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='cliente_avvisato_canale',
            field=models.CharField(blank=True, default='', help_text="Canale dell'ultimo avviso: 'whatsapp' o 'email'", max_length=20),
        ),
        migrations.AddField(
            model_name='ordine',
            name='cliente_avvisato_il',
            field=models.DateTimeField(blank=True, help_text="Quando l'operatore ha avvisato il cliente che l'auto e' pronta", null=True),
        ),
    ]
