# Generated by Django 4.2.29 on 2026-06-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0010_ordine_cliente_avvisato_canale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='cliente_avvisato_wa_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID del MessaggioWhatsApp inviato come avviso. Usato per leggere stato consegna (sent/delivered/read) sul badge.', max_length=128),
        ),
    ]
