# Generated by Django 4.2.29 on 2026-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0011_avviso_wa_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='cliente_avvisato_fallito',
            field=models.BooleanField(default=False, help_text="True se l'ultimo tentativo di avviso WhatsApp non e' andato a buon fine (Meta ha rigettato, finestra 24h chiusa, numero invalido, rete down). Il badge in /ordini/ diventa rosso e l'operatore puo' cliccare per ri-tentare."),
        ),
    ]
