# Generated by Django 4.2.29 on 2026-09-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatture', '0001_initial'),
        ('ordini', '0012_avviso_wa_fallito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='fattura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini', to='fatture.fattura'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='fattura_matricola',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordine',
            name='fattura_nota',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='fattura_targa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ordine',
            name='richiede_fattura',
            field=models.BooleanField(default=False),
        ),
    ]
