# Generated by Django 4.2.29 on 2026-09-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0013_ordine_fattura_ordine_fattura_matricola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='non_pagato_archiviato',
            field=models.BooleanField(default=False),
        ),
    ]
