# Generated by Django 4.2.29 on 2026-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0014_ordine_non_pagato_archiviato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='fattura_importo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
