# Generated by Django 4.2.29 on 2026-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0015_ordine_fattura_importo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='vendita_prodotti',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
