# Generated by Django 4.2.29 on 2026-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoImpianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodo', models.CharField(db_index=True, max_length=50)),
                ('tipo_evento', models.CharField(max_length=80)),
                ('valore', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento impianto',
                'verbose_name_plural': 'Eventi impianto',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nodo', 'tipo_evento', 'timestamp'], name='impianto_ev_nodo_a0a47e_idx')],
            },
        ),
    ]
