# Generated by Django 4.2.29 on 2026-06-13 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clienti', '0004_remove_email_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversazioneWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_e164', models.CharField(db_index=True, help_text='Numero E.164 con prefisso +, es. +393792337051', max_length=20, unique=True)),
                ('ultimo_messaggio_il', models.DateTimeField(auto_now=True, db_index=True)),
                ('ultimo_incoming_il', models.DateTimeField(blank=True, null=True)),
                ('non_letti', models.PositiveIntegerField(default=0)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente anagrafato associato. Null se numero sconosciuto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversazioni_wa', to='clienti.cliente')),
            ],
            options={
                'verbose_name': 'Conversazione WhatsApp',
                'verbose_name_plural': 'Conversazioni WhatsApp',
                'ordering': ['-ultimo_messaggio_il'],
            },
        ),
        migrations.CreateModel(
            name='MessaggioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direzione', models.CharField(choices=[('in', 'Entrata'), ('out', 'Uscita')], max_length=3)),
                ('corpo', models.TextField(blank=True, default='')),
                ('wa_message_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('stato', models.CharField(choices=[('received', 'Ricevuto'), ('sent', 'Inviato'), ('delivered', 'Recapitato'), ('read', 'Letto'), ('failed', 'Fallito')], default='received', max_length=12)),
                ('timestamp_meta', models.DateTimeField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('conversazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi', to='messaggi.conversazionewhatsapp')),
                ('operatore', models.ForeignKey(blank=True, help_text='Chi ha inviato il messaggio. Solo per direzione=out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messaggio WhatsApp',
                'verbose_name_plural': 'Messaggi WhatsApp',
                'ordering': ['creato_il'],
            },
        ),
        migrations.AddConstraint(
            model_name='messaggiowhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('wa_message_id__gt', '')), fields=('conversazione', 'wa_message_id'), name='unique_msg_per_conv_when_wa_id_set'),
        ),
    ]
