# Generated by Django 4.2.29 on 2026-06-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaggi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggiowhatsapp',
            name='media_id',
            field=models.CharField(blank=True, default='', help_text='ID media Meta. Usato dal proxy per scaricare il file.', max_length=128),
        ),
        migrations.AddField(
            model_name='messaggiowhatsapp',
            name='media_mime',
            field=models.CharField(blank=True, default='', help_text='Content-Type, es. audio/ogg, image/jpeg', max_length=80),
        ),
        migrations.AddField(
            model_name='messaggiowhatsapp',
            name='media_type',
            field=models.CharField(blank=True, choices=[('text', 'Testo'), ('audio', 'Audio'), ('image', 'Foto'), ('video', 'Video'), ('document', 'Documento'), ('sticker', 'Sticker'), ('location', 'Posizione')], default='text', max_length=12),
        ),
        migrations.AlterField(
            model_name='messaggiowhatsapp',
            name='corpo',
            field=models.TextField(blank=True, default='', help_text="Testo o caption del media. '[Audio]' come placeholder per voce."),
        ),
    ]
