# Generated by Django 4.2.23 on 2025-07-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privato', 'Privato'), ('azienda', 'Azienda')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('indirizzo', models.TextField(blank=True)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('ragione_sociale', models.CharField(blank=True, max_length=200)),
                ('partita_iva', models.CharField(blank=True, max_length=11)),
                ('codice_sdi', models.CharField(blank=True, max_length=7)),
                ('pec', models.EmailField(blank=True, max_length=254)),
                ('consenso_marketing', models.BooleanField(default=False)),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='PuntiFedelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punti_totali', models.IntegerField(default=0)),
                ('punti_utilizzati', models.IntegerField(default=0)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punti_fedelta', to='clienti.cliente')),
            ],
            options={
                'verbose_name_plural': 'Punti Fedeltà',
            },
        ),
        migrations.CreateModel(
            name='MovimentoPunti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('accumulo', 'Accumulo'), ('utilizzo', 'Utilizzo'), ('scadenza', 'Scadenza'), ('bonus', 'Bonus')], max_length=20)),
                ('punti', models.IntegerField(help_text='Positivi per accumulo, negativi per utilizzo')),
                ('descrizione', models.CharField(max_length=200)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_punti', to='clienti.cliente')),
            ],
            options={
                'verbose_name_plural': 'Movimenti Punti',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
