# Generated by Django 4.2.23 on 2025-07-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentopunti',
            name='ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordini.ordine'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
