# Generated by Django 4.2.29 on 2026-07-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0004_remove_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='blocca_marketing',
            field=models.BooleanField(default=False, help_text='Escluso da ogni messaggio promozionale.', verbose_name='Non contattare (opt-out marketing)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='blocca_marketing_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='blocca_marketing_motivo',
            field=models.CharField(blank=True, default='', help_text="Es. 'STOP via WhatsApp', 'richiesta telefonica', ...", max_length=200),
        ),
    ]
