# Generated by Django 4.2.29 on 2026-09-17 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clienti', '0005_blocca_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('stato', models.CharField(choices=[('da_pagare', 'Da pagare'), ('pagata', 'Pagata'), ('archiviata', 'Archiviata')], default='da_pagare', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('pagata_il', models.DateTimeField(blank=True, null=True)),
                ('archiviata_il', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatture', to='clienti.cliente')),
                ('creata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatture_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fattura',
                'verbose_name_plural': 'Fatture',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
