# Generated by Django 4.2.29 on 2026-09-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigaFattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.CharField(max_length=200)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='fatture.fattura')),
            ],
            options={
                'verbose_name': 'Riga fattura',
                'verbose_name_plural': 'Righe fattura',
                'ordering': ['data', 'id'],
            },
        ),
    ]
