# Generated by Django 4.2.29 on 2026-09-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0005_blocca_marketing'),
        ('fatture', '0002_rigafattura'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigafattura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voci_da_fatturare', to='clienti.cliente'),
        ),
        migrations.AlterField(
            model_name='rigafattura',
            name='fattura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe', to='fatture.fattura'),
        ),
    ]
