# Generated by Django 4.2.29 on 2026-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatture', '0003_rigafattura_cliente_alter_rigafattura_fattura'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigafattura',
            name='matricola',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rigafattura',
            name='nota',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rigafattura',
            name='targa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='rigafattura',
            name='tipo_auto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
