# Generated by Django 4.2.29 on 2026-07-23 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0005_blocca_marketing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniMonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendita_online_attiva', models.BooleanField(default=False, help_text="Mostra i pacchetti acquistabili nell'area cliente.")),
                ('stripe_attivo', models.BooleanField(default=False)),
                ('paypal_attivo', models.BooleanField(default=False)),
                ('cooldown_lavaggio_sec', models.PositiveSmallIntegerField(default=15, help_text='Secondi minimi tra due avvii dello stesso cliente sullo stesso nodo (anti double-tap).')),
                ('testo_pagina_acquisto', models.TextField(blank=True, default='', help_text='Testo libero mostrato sopra i pacchetti in Le mie monete.')),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni monete',
                'verbose_name_plural': 'Impostazioni monete',
            },
        ),
        migrations.CreateModel(
            name='NodoImpianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Segmento topic MQTT (es. 'pista2'): deve combaciare con l'MQTT prefix autolavaggio/<slug> del dispositivo.", unique=True)),
                ('nome', models.CharField(help_text="Es. 'Pista 2 self-service'", max_length=100)),
                ('switch_id', models.PositiveSmallIntegerField(default=1, help_text="Uscita del rele' gettoniera sullo Shelly (pista2: OUT2 = id 1).")),
                ('monete_per_impulso', models.PositiveIntegerField(default=1, help_text='Quante monete virtuali costa UN impulso su questo nodo.')),
                ('max_impulsi', models.PositiveSmallIntegerField(default=10, help_text='Tetto di impulsi per singola operazione di avvio.')),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.PositiveSmallIntegerField(default=0, help_text='Ordinamento nelle liste (0 = primo).')),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Nodo impianto',
                'verbose_name_plural': 'Nodi impianto',
                'ordering': ['ordine', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='PacchettoMonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('monete', models.PositiveIntegerField()),
                ('bonus', models.PositiveIntegerField(default=0, help_text='Monete extra regalate con questo pacchetto.')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pacchetto monete',
                'verbose_name_plural': 'Pacchetti monete',
                'ordering': ['ordine', 'prezzo'],
            },
        ),
        migrations.CreateModel(
            name='SaldoMonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_monete', to='clienti.cliente')),
            ],
            options={
                'verbose_name': 'Saldo monete',
                'verbose_name_plural': 'Saldi monete',
            },
        ),
        migrations.CreateModel(
            name='AcquistoMonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monete', models.PositiveIntegerField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=10)),
                ('provider_ref', models.CharField(blank=True, db_index=True, default='', help_text='Stripe: id Checkout Session (cs_...); PayPal: order id.', max_length=255)),
                ('stato', models.CharField(choices=[('creato', 'Creato'), ('pagato', 'Pagato'), ('accreditato', 'Accreditato'), ('annullato', 'Annullato'), ('fallito', 'Fallito')], default='creato', max_length=15)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisti_monete', to='clienti.cliente')),
                ('pacchetto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monete.pacchettomonete')),
            ],
            options={
                'verbose_name': 'Acquisto monete',
                'verbose_name_plural': 'Acquisti monete',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoMoneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acquisto_online', 'Acquisto online'), ('ricarica_cassa', 'Ricarica in cassa'), ('regalo', 'Regalo'), ('promozione', 'Promozione'), ('lavaggio', 'Avvio lavaggio'), ('storno', 'Storno'), ('rettifica', 'Rettifica manuale'), ('abbonamento', 'Abbonamento')], max_length=20)),
                ('monete', models.IntegerField(help_text='Positivo = accredito, negativo = addebito.')),
                ('saldo_dopo', models.PositiveIntegerField()),
                ('descrizione', models.CharField(max_length=200)),
                ('impulsi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, help_text='EUR incassati (per ricarica_cassa): riconciliabile con finanze.', max_digits=7, null=True)),
                ('chiave_idempotenza', models.CharField(blank=True, default='', max_length=64)),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acquisto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monete.acquistomonete')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_monete', to='clienti.cliente')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monete.nodoimpianto')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento monete',
                'verbose_name_plural': 'Movimenti monete',
                'ordering': ['-creato_il'],
                'indexes': [models.Index(fields=['cliente', '-creato_il'], name='monete_movi_cliente_78c6bc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='movimentomoneta',
            constraint=models.UniqueConstraint(condition=models.Q(('chiave_idempotenza', ''), _negated=True), fields=('chiave_idempotenza',), name='uq_movimento_idempotenza'),
        ),
        migrations.AddConstraint(
            model_name='acquistomonete',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider', 'provider_ref'), name='uq_acquisto_provider_ref'),
        ),
    ]
