# Generated by Django 4.2.29 on 2026-07-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodoimpianto',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodoimpianto',
            name='online_aggiornato_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
