# Generated by Django 4.2.29 on 2026-07-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monete', '0002_nodoimpianto_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionimonete',
            name='acquisto_max_monete',
            field=models.PositiveSmallIntegerField(default=200, help_text='Massimo monete acquistabili in una volta.'),
        ),
        migrations.AddField(
            model_name='impostazionimonete',
            name='acquisto_min_monete',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimo monete acquistabili in una volta.'),
        ),
        migrations.AddField(
            model_name='impostazionimonete',
            name='prezzo_moneta',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Prezzo in euro di UNA moneta per l'acquisto a quantita' libera (i pacchetti hanno il loro prezzo).", max_digits=5),
        ),
    ]
