# Generated by Django 4.2.29 on 2026-07-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monete', '0003_impostazionimonete_acquisto_max_monete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodoimpianto',
            name='pausa_impulsi_sec',
            field=models.FloatField(default=2.0, help_text="Pausa tra un impulso e il successivo (secondi). DEVE essere maggiore dell'auto-off del rele' (1s), altrimenti il comando successivo arriva a rele' ancora chiuso e gli impulsi si fondono in uno solo (la gettoniera conta i fronti di salita)."),
        ),
    ]
