# Generated by Django 4.2.29 on 2026-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monete', '0004_nodoimpianto_pausa_impulsi_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentomoneta',
            name='contatore_atteso',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentomoneta',
            name='contatore_prima',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentomoneta',
            name='impulsi_contati',
            field=models.BigIntegerField(blank=True, help_text="Avanzamento del contatore osservato dopo l'invio.", null=True),
        ),
        migrations.AddField(
            model_name='movimentomoneta',
            name='verifica',
            field=models.CharField(blank=True, choices=[('', '-'), ('in_attesa', 'In attesa conferma'), ('ok', 'Confermato dal contatore'), ('discrepanza', 'DISCREPANZA'), ('non_verificabile', 'Non verificabile')], default='', max_length=20),
        ),
    ]
