# Generated by Django 4.2.29 on 2026-07-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monete', '0005_movimentomoneta_contatore_atteso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaImpianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.CharField(blank=True, default='', help_text='Riga descrittiva mostrata sotto il nome della zona.', max_length=200)),
                ('ordine', models.PositiveSmallIntegerField(default=0, help_text='Ordinamento delle zone (0 = prima).')),
            ],
            options={
                'verbose_name': 'Zona impianto',
                'verbose_name_plural': 'Zone impianto',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='impostazionimonete',
            name='testo_avvio_lavaggio',
            field=models.CharField(blank=True, default='Usa le tue monete per avviare spazzole, aspiratori e lance direttamente dal telefono: scegli la postazione, decidi gli impulsi e premi Avvia.', help_text='Breve descrizione mostrata nella card "Avvia un lavaggio" all\'ingresso dell\'area cliente.', max_length=250),
        ),
        migrations.AddField(
            model_name='nodoimpianto',
            name='descrizione',
            field=models.CharField(blank=True, default='', help_text='Riga descrittiva mostrata al cliente sotto il nome.', max_length=200),
        ),
        migrations.AddField(
            model_name='nodoimpianto',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona in cui compare la postazione (es. Spazzole).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodi', to='monete.zonaimpianto'),
        ),
    ]
