# Generated by Django 4.2.29 on 2026-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monete', '0006_zonaimpianto_impostazionimonete_testo_avvio_lavaggio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentomoneta',
            name='tipo',
            field=models.CharField(choices=[('acquisto_online', 'Acquisto online'), ('ricarica_cassa', 'Ricarica in cassa'), ('regalo', 'Regalo'), ('promozione', 'Promozione'), ('lavaggio', 'Avvio lavaggio'), ('storno', 'Storno'), ('rettifica', 'Rettifica manuale'), ('abbonamento', 'Abbonamento'), ('premio', 'Premio percorso')], max_length=20),
        ),
    ]
